### ISSUE TITLE
Remove the full-screen button

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/tic-tac-toe#11]
The full-screen button at the bottom-left corner should be hidden when PWA is installed. As PWA will already be in full-screen mode.

**Comment by agkeshav** [comment]
I can do this for you assign me this work.

**Comment by agkeshav** [comment]
can you please time how to run this project in our system?

**Comment by yashchaudhari008** [comment]
> can you please time how to run this project in our system?
> 

It's a react app. You need node.js installed.

npm install
npm run start

**Comment by Aditya0049** [comment]
Solved-------The full-screen button at the bottom-left corner should be hidden when PWA is installed. As PWA will already be in full-screen mode.

https://user-images.githubusercontent.com/88885329/189996105-1cd3e4cc-4121-4c8d-b31f-cfb9e6863bd1.mp4

**Comment by yashchaudhari008** [comment]
> Solved-------The full-screen button at the bottom-left corner should be hidden when PWA is installed. As PWA will already be in full-screen mode.
> 
> https://user-images.githubusercontent.com/88885329/189996105-1cd3e4cc-4121-4c8d-b31f-cfb9e6863bd1.mp4
> 
> 
> 

Good Work but full-screen icon should be hidden only when the app is installed and not when it's running on a mobile device.

**Comment by Jaivrat12** [comment]
Hello there, @yashchaudhari008! I can solve this issue!!!
Can you please assign this issue to me?

**Comment by Jaivrat12** [comment]
Hey there @yashchaudhari008,
I made a Pull Request #17 for this issue, can you please review it?
Thanks!
